---
- name: 🚀 Deploy Quiz Whiz Kid Docker App
  hosts: web
  become: true

  vars:
    container_name: quiz-whiz-kid
    image_name: stutig123/quiz-whiz-kid:latest  # Replace with your Docker Hub image name
    exposed_port: 80

  tasks:

    - name: Ensure required apt packages are installed
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Log in to DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Stop and remove existing container (if running)
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ exposed_port }}:80"
