---
- name: Deploy Quiz Whiz App on EC2
  hosts: web
  become: true

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Pull latest Docker image from Docker Hub
      command: docker pull stutigambhir/quiz-whiz:latest

    - name: Stop existing container (if running)
      shell: |
        docker ps -q --filter "name=quiz-whiz" | grep -q . && docker stop quiz-whiz || true

    - name: Remove existing container (if exists)
      shell: |
        docker ps -a -q --filter "name=quiz-whiz" | grep -q . && docker rm quiz-whiz || true

    - name: Run Quiz Whiz container
      command: docker run -d -p 80:3000 --name quiz-whiz stutigambhir/quiz-whiz:latest
