name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read  # Read repository contents
  security-events: write  # Write permissions for security events

jobs:
  terraform:
    name: 🔧 Terraform Infrastructure Provisioning
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init
        working-directory: hospital-terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: hospital-terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"


  ansible:
    runs-on: ubuntu-latest
    needs: terraform  # Ensure Ansible runs after Terraform finishes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create SSH private key file
        run: |
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa  # Create SSH key file from GitHub Secrets
          chmod 600 $HOME/.ssh/id_rsa  # Set secure permissions for the SSH key

      - name: Update Inventory with EC2 IP
        run: |
          sed -i "s/{{ EC2_PUBLIC_IP }}/$EC2_PUBLIC_IP/" ansible/inventory.ini
          # Replace the placeholder {{ EC2_PUBLIC_IP }} in inventory.ini with the actual EC2 IP

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
